import logging
from database import get_connection

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def insert_vendor(vendor_name):
    """
    Link 1: Insert a single row and return the generated ID.
    """
    query = "INSERT INTO vendors (vendor_name) VALUES (%s) RETURNING vendor_id;"
    vendor_id = None
    
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (vendor_name,))
            # Fetch the ID generated by the SERIAL constraint
            vendor_id = cur.fetchone()[0]
            conn.commit()
            logger.info(f"Inserted single vendor with ID: {vendor_id}")
            
    return vendor_id

def insert_many_vendors(vendor_list):
    """
    Link 1: Insert multiple rows efficiently using executemany.
    'vendor_list' should be a list of tuples: [('Vendor A',), ('Vendor B',)]
    """
    query = "INSERT INTO vendors (vendor_name) VALUES (%s);"
    
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.executemany(query, vendor_list)
            conn.commit()
            logger.info(f"Inserted {len(vendor_list)} vendors in batch.")

def update_vendor(vendor_id, new_name):
    """
    Link 2: Update existing data and return the number of affected rows.
    """
    query = "UPDATE vendors SET vendor_name = %s WHERE vendor_id = %s;"
    updated_rows = 0
    
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (new_name, vendor_id))
            # rowcount tells us how many rows were actually updated
            updated_rows = cur.rowcount
            conn.commit()
            logger.info(f"Updated {updated_rows} rows.")
            
    return updated_rows

def get_vendors():
    """
    Link 3: Query data using fetchall() and fetchmany().
    """
    query = "SELECT vendor_id, vendor_name FROM vendors ORDER BY vendor_id;"
    
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query)
            
            # Fetch all rows at once
            logger.info("--- Fetching all vendors ---")
            rows = cur.fetchall()
            for row in rows:
                logger.info(f"ID: {row[0]}, Name: {row[1]}")

def delete_part(part_id):
    """
    Link 8: Delete data and return the number of deleted rows.
    """
    query = "DELETE FROM parts WHERE part_id = %s;"
    deleted_rows = 0
    
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (part_id,))
            deleted_rows = cur.rowcount
            conn.commit()
            logger.info(f"Deleted {deleted_rows} parts.")
            
    return deleted_rows

if __name__ == "__main__":
    # Test the CRUD operations pipeline
    logger.info("=== STARTING CRUD TESTS ===")
    v_id = insert_vendor("3M Company")
    insert_many_vendors([("AKM Semiconductor",), ("Asahi Glass Co Ltd",), ("Daikin Industries",)])
    update_vendor(v_id, "3M Corp (Updated)")
    get_vendors()
    # Note: delete_part is not called here to keep data safe, but the logic is ready.